[package]
name = "cryptoooor"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.4"
aes-gcm = "0.10.3"
aes-gcm-siv = "0.11.1"
bincode = "1.3.3"
generic-array = "1.1.0"
rprompt = "2.1.1"
scrypt = "0.11.0"
typenum = "1.17.0"
