[package]
name = "cw"
version = "0.0.0"
license = "MIT"
repository = "https://github.com/pindjouf/perso_rustlings.git"
description = "A wc clone"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
patharg = "0.4.0"
